import { create } from 'zustand';

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: string;
  subcategory: string;
  image: string;
  rating: number;
  reviews: number;
  sold: number;
  deliveryTime: string;
  platform: string;
  region: string;
  tags: string[];
  stock: number;
  featured: boolean;
}

export interface CartItem {
  product: Product;
  quantity: number;
}

interface StoreState {
  cart: CartItem[];
  cartOpen: boolean;
  authOpen: boolean;
  selectedProduct: Product | null;
  productDetailOpen: boolean;
  user: { id: string; name: string; email: string } | null;
  searchQuery: string;
  selectedCategory: string;
  selectedSubcategory: string;
  sortBy: string;
  addToCart: (product: Product) => void;
  removeFromCart: (productId: string) => void;
  updateQuantity: (productId: string, quantity: number) => void;
  clearCart: () => void;
  setCartOpen: (open: boolean) => void;
  setAuthOpen: (open: boolean) => void;
  setSelectedProduct: (product: Product | null) => void;
  setProductDetailOpen: (open: boolean) => void;
  setUser: (user: { id: string; name: string; email: string } | null) => void;
  setSearchQuery: (query: string) => void;
  setSelectedCategory: (category: string) => void;
  setSelectedSubcategory: (subcategory: string) => void;
  setSortBy: (sort: string) => void;
  cartTotal: () => number;
  cartCount: () => number;
}

export const useStore = create<StoreState>((set, get) => ({
  cart: [],
  cartOpen: false,
  authOpen: false,
  selectedProduct: null,
  productDetailOpen: false,
  user: null,
  searchQuery: '',
  selectedCategory: 'all',
  selectedSubcategory: 'all',
  sortBy: 'popular',

  addToCart: (product) =>
    set((state) => {
      const existing = state.cart.find((item) => item.product.id === product.id);
      if (existing) {
        return {
          cart: state.cart.map((item) =>
            item.product.id === product.id
              ? { ...item, quantity: item.quantity + 1 }
              : item
          ),
        };
      }
      return { cart: [...state.cart, { product, quantity: 1 }] };
    }),

  removeFromCart: (productId) =>
    set((state) => ({
      cart: state.cart.filter((item) => item.product.id !== productId),
    })),

  updateQuantity: (productId, quantity) =>
    set((state) => ({
      cart:
        quantity <= 0
          ? state.cart.filter((item) => item.product.id !== productId)
          : state.cart.map((item) =>
              item.product.id === productId ? { ...item, quantity } : item
            ),
    })),

  clearCart: () => set({ cart: [] }),
  setCartOpen: (open) => set({ cartOpen: open }),
  setAuthOpen: (open) => set({ authOpen: open }),
  setSelectedProduct: (product) => set({ selectedProduct: product }),
  setProductDetailOpen: (open) => set({ productDetailOpen: open }),
  setUser: (user) => set({ user }),
  setSearchQuery: (query) => set({ searchQuery: query }),
  setSelectedCategory: (category) => set({ selectedCategory: category, selectedSubcategory: 'all' }),
  setSelectedSubcategory: (subcategory) => set({ selectedSubcategory: subcategory }),
  setSortBy: (sort) => set({ sortBy: sort }),

  cartTotal: () =>
    get().cart.reduce((total, item) => total + item.product.price * item.quantity, 0),

  cartCount: () =>
    get().cart.reduce((count, item) => count + item.quantity, 0),
}));

export const CATEGORIES = [
  { id: 'gaming', name: 'Gaming', icon: 'Gamepad2', color: 'from-purple-500 to-pink-500' },
  { id: 'streaming', name: 'Streaming', icon: 'Tv', color: 'from-red-500 to-orange-500' },
  { id: 'accounts', name: 'Cuentas', icon: 'UserCircle', color: 'from-emerald-500 to-teal-500' },
  { id: 'giftcards', name: 'Tarjetas Regalo', icon: 'Gift', color: 'from-amber-500 to-yellow-500' },
  { id: 'software', name: 'Software', icon: 'AppWindow', color: 'from-cyan-500 to-blue-500' },
  { id: 'subscriptions', name: 'Suscripciones', icon: 'RefreshCw', color: 'from-violet-500 to-purple-500' },
];

export const SUBCATEGORIES: Record<string, string[]> = {
  gaming: ['Skins', 'V-Bucks', 'Robux', 'Monedas', 'Pases de Batalla', 'Cuentas', 'Items'],
  streaming: ['Netflix', 'Spotify', 'Disney+', 'HBO Max', 'Crunchyroll', 'Prime Video', 'Paramount+', 'Apple TV+'],
  accounts: ['Gaming', 'Streaming', 'Redes Sociales', 'Software'],
  giftcards: ['PlayStation', 'Xbox', 'Nintendo', 'Steam', 'Apple', 'Google Play', 'Amazon', 'Netflix', 'Epic Games'],
  software: ['Licencias Windows', 'Office', 'Antivirus', 'VPN', 'Herramientas'],
  subscriptions: ['Spotify', 'YouTube Premium', 'Discord Nitro', 'Twitch', 'Cloud Gaming', 'Canva Pro'],
};

export const PRODUCTS: Product[] = [
// =========================================
// GAMING (50 productos)
// =========================================
{ id: 'g1', name: '1000 V-Bucks - Fortnite', description: 'Moneda virtual para Fortnite. Compra skins, pases de batalla y mas en la tienda del juego.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'V-Bucks', image: '/products/gen/fortnite.png', rating: 4.8, reviews: 12500, sold: 89000, deliveryTime: 'Entrega instantanea', platform: 'Fortnite', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: true },
{ id: 'g2', name: '2800 V-Bucks - Fortnite', description: 'Paquete de 2800 V-Bucks para Fortnite. Ideal para comprar el Pase de Batalla y varias skins.', price: 12.99, originalPrice: 24.99, category: 'gaming', subcategory: 'V-Bucks', image: '/products/gen/fortnite.png', rating: 4.8, reviews: 8200, sold: 62000, deliveryTime: 'Entrega instantanea', platform: 'Fortnite', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g3', name: '5000 V-Bucks - Fortnite', description: 'Paquete grande de 5000 V-Bucks. El mejor valor para compradores frecuentes de Fortnite.', price: 22.99, originalPrice: 39.99, category: 'gaming', subcategory: 'V-Bucks', image: '/products/gen/fortnite.png', rating: 4.9, reviews: 5600, sold: 42000, deliveryTime: 'Entrega instantanea', platform: 'Fortnite', region: 'Global', tags: ['oferta', 'popular'], stock: 999, featured: false },
{ id: 'g4', name: '13500 V-Bucks - Fortnite', description: 'Paquete mega de 13500 V-Bucks. Maximo valor para coleccionistas de skins.', price: 59.99, originalPrice: 99.99, category: 'gaming', subcategory: 'V-Bucks', image: '/products/gen/fortnite.png', rating: 4.9, reviews: 3200, sold: 18000, deliveryTime: 'Entrega instantanea', platform: 'Fortnite', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g5', name: '800 Robux - Roblox', description: 'Robux para Roblox. Personaliza tu avatar, compra game passes y items exclusivos.', price: 3.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Robux', image: '/products/gen/roblox.png', rating: 4.7, reviews: 9800, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'Roblox', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: true },
{ id: 'g6', name: '1700 Robux - Roblox', description: 'Paquete de 1700 Robux. Suficiente para multiples game passes y accesorios premium.', price: 7.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Robux', image: '/products/gen/roblox.png', rating: 4.7, reviews: 6500, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Roblox', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g7', name: '4500 Robux - Roblox', description: 'Paquete premium de 4500 Robux para los jugadores mas serios de Roblox.', price: 19.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Robux', image: '/products/gen/roblox.png', rating: 4.8, reviews: 4200, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'Roblox', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g8', name: 'Pase de Batalla - Temporada Actual', description: '100 niveles de premios exclusivos durante toda la temporada de Fortnite.', price: 5.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Pases de Batalla', image: '/products/gen/fortnite.png', rating: 4.6, reviews: 5600, sold: 45000, deliveryTime: 'Entrega instantanea', platform: 'Fortnite', region: 'Global', tags: ['tendencia'], stock: 999, featured: true },
{ id: 'g9', name: 'Skin Legendaria - Valorant', description: 'Skin premium con efectos especiales y animacion unica para tu arma favorita en Valorant.', price: 7.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Skins', image: '/products/gen/valorant.png', rating: 4.9, reviews: 2100, sold: 15000, deliveryTime: 'Entrega instantanea', platform: 'Valorant', region: 'Global', tags: ['premium'], stock: 200, featured: true },
{ id: 'g10', name: 'VP 5000 - Valorant Points', description: '5000 Valorant Points para desbloquear skins, el pase de batalla y radianite.', price: 14.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Skins', image: '/products/gen/valorant.png', rating: 4.8, reviews: 3800, sold: 25000, deliveryTime: 'Entrega instantanea', platform: 'Valorant', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g11', name: 'Cuenta Premium Minecraft', description: 'Cuenta premium de Minecraft Java Edition con acceso completo a multijugador y skins.', price: 4.99, originalPrice: 26.95, category: 'gaming', subcategory: 'Cuentas', image: '/products/gen/minecraft.png', rating: 4.4, reviews: 7800, sold: 62000, deliveryTime: '1-24 horas', platform: 'Minecraft', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 150, featured: false },
{ id: 'g12', name: 'Minecraft Bedrock Premium', description: 'Cuenta premium Bedrock para Windows 10, consolas y movil. Multijugador incluido.', price: 5.99, originalPrice: 26.95, category: 'gaming', subcategory: 'Cuentas', image: '/products/gen/minecraft.png', rating: 4.5, reviews: 5200, sold: 38000, deliveryTime: '1-24 horas', platform: 'Minecraft', region: 'Global', tags: ['oferta'], stock: 150, featured: false },
{ id: 'g13', name: 'RP League of Legends - 1380', description: 'Riot Points para League of Legends. Desbloquea campeones, skins y chromas exclusivos.', price: 5.49, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/lol.png', rating: 4.6, reviews: 4200, sold: 35000, deliveryTime: 'Entrega instantanea', platform: 'League of Legends', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'g14', name: 'RP League of Legends - 3500', description: 'Paquete de 3500 Riot Points. Suficiente para varias skins epicas y chromas.', price: 12.99, originalPrice: 24.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/lol.png', rating: 4.6, reviews: 3800, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'League of Legends', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g15', name: 'Genesis Crystal Pack - Genshin Impact', description: 'Paquete de cristales genesis. Obtene personajes 5 estrellas y armas legendarias.', price: 7.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/genshin.png', rating: 4.8, reviews: 6100, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Genshin Impact', region: 'Global', tags: ['oferta', 'tendencia'], stock: 999, featured: true },
{ id: 'g16', name: 'Blessing of the Welkin Moon - Genshin', description: 'Suscripcion mensual de Genshin Impact: 300 cristales diarios durante 30 dias.', price: 2.99, originalPrice: 4.99, category: 'gaming', subcategory: 'Pases de Batalla', image: '/products/gen/genshin.png', rating: 4.9, reviews: 8900, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'Genshin Impact', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 'g17', name: 'Monedas Apex Legends - 1000', description: 'Monedas para Apex Legends. Desbloquea skins de armas, legendas y objetos del pase de batalla.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/apex.png', rating: 4.6, reviews: 3800, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Apex Legends', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'g18', name: 'Monedas Apex Legends - 2150', description: 'Paquete de 2150 monedas Apex. Desbloquea skins legendarias y el pase de batalla completo.', price: 9.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/apex.png', rating: 4.7, reviews: 2800, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Apex Legends', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g19', name: 'UC PUBG Mobile - 600', description: 'Unlimited Cash para PUBG Mobile. Compra skins, armas y el Royal Pass con descuento.', price: 4.49, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/pubgm.png', rating: 4.5, reviews: 5200, sold: 41000, deliveryTime: 'Entrega instantanea', platform: 'PUBG Mobile', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'g20', name: 'UC PUBG Mobile - 3250', description: 'Paquete grande de 3250 UC. Ideal para Royal Pass Elite y skins premium de armas.', price: 18.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/pubgm.png', rating: 4.6, reviews: 3400, sold: 24000, deliveryTime: 'Entrega instantanea', platform: 'PUBG Mobile', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g21', name: 'Diamantes Free Fire - 1000', description: 'Diamantes para Free Fire. Desbloquea personajes, skins de armas y el pase de elite.', price: 3.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/freefire.png', rating: 4.4, reviews: 9200, sold: 78000, deliveryTime: 'Entrega instantanea', platform: 'Free Fire', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 'g22', name: 'Diamantes Free Fire - 5600', description: 'Paquete mega de 5600 diamantes para Free Fire. Maximo valor para jugadores frecuentes.', price: 19.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/freefire.png', rating: 4.5, reviews: 4100, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Free Fire', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g23', name: 'Cuenta Among Us - Skins Completas', description: 'Cuenta con todas las skins, mascotas y sombreros desbloqueados de Among Us.', price: 2.99, originalPrice: 14.99, category: 'gaming', subcategory: 'Cuentas', image: '/products/gen/amongus.png', rating: 4.2, reviews: 4500, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Among Us', region: 'Global', tags: ['oferta'], stock: 200, featured: false },
{ id: 'g24', name: 'Gemas Clash Royale - 1400', description: 'Gemas premium para Clash Royale. Desbloquea cofres magicos y mejora tus cartas.', price: 3.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/clashroyale.png', rating: 4.5, reviews: 6700, sold: 55000, deliveryTime: 'Entrega instantanea', platform: 'Clash Royale', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'g25', name: 'Diamantes Mobile Legends - 400', description: 'Diamantes para Mobile Legends Bang Bang. Compra heroes, skins y el magic wheel.', price: 3.49, originalPrice: 8.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/mobilelegends.png', rating: 4.5, reviews: 7100, sold: 58000, deliveryTime: 'Entrega instantanea', platform: 'Mobile Legends', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'g26', name: 'Diamantes Mobile Legends - 2200', description: 'Paquete de 2200 diamantes MLBB. Skins epicas, heroes premium y el magic wheel.', price: 14.99, originalPrice: 39.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/mobilelegends.png', rating: 4.6, reviews: 3800, sold: 26000, deliveryTime: 'Entrega instantanea', platform: 'Mobile Legends', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g27', name: 'Gemas Brawl Stars - 170', description: 'Gemas premium para Brawl Stars. Desbloquea el Brawl Pass y cajas mega de personajes.', price: 3.49, originalPrice: 8.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/brawlstars.png', rating: 4.7, reviews: 8400, sold: 67000, deliveryTime: 'Entrega instantanea', platform: 'Brawl Stars', region: 'Global', tags: ['popular', 'tendencia'], stock: 999, featured: true },
{ id: 'g28', name: 'Gemas Brawl Stars - 1700', description: 'Paquete grande de 1700 gemas para Brawl Stars. Desbloquea multiples Brawl Pass y boxes.', price: 18.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/brawlstars.png', rating: 4.7, reviews: 4500, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Brawl Stars', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g29', name: 'CS2 Skins - Paquete Premium', description: 'Seleccion de skins premium para Counter-Strike 2. Incluye armas con acabados raros.', price: 9.99, originalPrice: 24.99, category: 'gaming', subcategory: 'Skins', image: '/products/gen/cs2.png', rating: 4.8, reviews: 5200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Counter-Strike 2', region: 'Global', tags: ['popular', 'tendencia'], stock: 150, featured: true },
{ id: 'g30', name: 'CS2 - Case Key Bundle x5', description: '5 llaves para cajas de CS2. Abre cajas y obten skins de armas al azar.', price: 7.99, originalPrice: 14.99, category: 'gaming', subcategory: 'Items', image: '/products/gen/cs2.png', rating: 4.3, reviews: 3400, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Counter-Strike 2', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g31', name: 'GTA V - Shark Card Megalodon', description: 'Shark Card Megalodon de $8M para GTA Online. Compra propiedades y vehiculos de lujo.', price: 12.99, originalPrice: 39.99, category: 'gaming', subcategory: 'Items', image: '/products/gen/gtav.png', rating: 4.6, reviews: 4100, sold: 29000, deliveryTime: 'Entrega instantanea', platform: 'GTA V', region: 'Global', tags: ['oferta', 'tendencia'], stock: 500, featured: false },
{ id: 'g32', name: 'GTA V - Shark Card Whale', description: 'Shark Card Whale de $3.5M para GTA Online. Ideal para compras intermedias.', price: 6.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Items', image: '/products/gen/gtav.png', rating: 4.5, reviews: 3500, sold: 24000, deliveryTime: 'Entrega instantanea', platform: 'GTA V', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g33', name: '2400 CoD Points - Warzone', description: 'CoD Points para Call of Duty Warzone y MW3. Compra battle pass y bundles.', price: 7.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/cod.png', rating: 4.5, reviews: 3800, sold: 25000, deliveryTime: 'Entrega instantanea', platform: 'Call of Duty', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'g34', name: 'Cuenta Premium Warzone/MW3', description: 'Cuenta con todos los DLCs y codigos de Call of Duty Warzone desbloqueados.', price: 5.99, originalPrice: 69.99, category: 'gaming', subcategory: 'Cuentas', image: '/products/gen/cod.png', rating: 4.3, reviews: 2800, sold: 18500, deliveryTime: '1-6 horas', platform: 'Call of Duty', region: 'Global', tags: ['oferta'], stock: 100, featured: false },
{ id: 'g35', name: 'Oneiric Shard Pack - Honkai Star Rail', description: 'Paquete de fragmentos oniricos. Obtene personajes 5 estrellas y armas legendarias.', price: 8.99, originalPrice: 24.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/honkai.png', rating: 4.9, reviews: 7500, sold: 55000, deliveryTime: 'Entrega instantanea', platform: 'Honkai Star Rail', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 'g36', name: 'Express Supply Pass - Honkai Star Rail', description: 'Pase mensual de Honkai Star Rail. 300 fragmentos oniricos diarios durante 30 dias.', price: 2.99, originalPrice: 4.99, category: 'gaming', subcategory: 'Pases de Batalla', image: '/products/gen/honkai.png', rating: 4.9, reviews: 6800, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Honkai Star Rail', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 'g37', name: 'Astrite Pack - Wuthering Waves', description: 'Paquete de astritas para Wuthering Waves. Invoca resonadores de alta rareza.', price: 7.49, originalPrice: 19.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/wuthering.png', rating: 4.7, reviews: 4200, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Wuthering Waves', region: 'Global', tags: ['tendencia', 'oferta'], stock: 999, featured: false },
{ id: 'g38', name: '2800 Monedas EA FC 25', description: 'Monedas para EA FC 25 Ultimate Team. Construye tu equipo suenado con jugadores top.', price: 9.99, originalPrice: 24.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/eafc25.png', rating: 4.5, reviews: 3400, sold: 28000, deliveryTime: '5-30 minutos', platform: 'EA FC 25', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g39', name: '5600 Monedas EA FC 25', description: 'Paquete grande de 5600 monedas EA FC 25. Ideal para fichar jugadores de elite.', price: 18.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/eafc25.png', rating: 4.5, reviews: 2800, sold: 20000, deliveryTime: '5-30 minutos', platform: 'EA FC 25', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g40', name: 'Gemas Clash of Clans - 1400', description: 'Gemas para Clash of Clans. Acelera construcciones, entrena tropas y compra decoraciones.', price: 3.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/coc.png', rating: 4.6, reviews: 7200, sold: 58000, deliveryTime: 'Entrega instantanea', platform: 'Clash of Clans', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'g41', name: 'Gemas Clash of Clans - 5000', description: 'Paquete de 5000 gemas COC. Acelera tu aldea al maximo nivel rapidamente.', price: 12.99, originalPrice: 34.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/coc.png', rating: 4.7, reviews: 4800, sold: 35000, deliveryTime: 'Entrega instantanea', platform: 'Clash of Clans', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g42', name: 'Wild Tokens - League of Legends Wild Rift', description: 'Wild Tokens para LoL Wild Rift. Desbloquea campeones y skins exclusivas de movil.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/wildrift.png', rating: 4.5, reviews: 3200, sold: 24000, deliveryTime: 'Entrega instantanea', platform: 'Wild Rift', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g43', name: 'Cuenta Diablo IV - Edicion Estandar', description: 'Cuenta con Diablo IV completo. Incluye acceso al juego base y todas las temporadas.', price: 9.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Cuentas', image: '/products/gen/diablo4.png', rating: 4.6, reviews: 3800, sold: 22000, deliveryTime: '1-6 horas', platform: 'Diablo IV', region: 'Global', tags: ['oferta'], stock: 100, featured: false },
{ id: 'g44', name: '1000 Overwatch Coins', description: 'Monedas para Overwatch 2. Desbloquea skins legendarias, el pase de batalla y mas.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/overwatch2.png', rating: 4.5, reviews: 2800, sold: 18000, deliveryTime: 'Entrega instantanea', platform: 'Overwatch 2', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'g45', name: '5000 Overwatch Coins', description: 'Paquete grande de 5000 monedas OW2. Multiples skins premium y el pase completo.', price: 19.99, originalPrice: 39.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/overwatch2.png', rating: 4.6, reviews: 2100, sold: 14000, deliveryTime: 'Entrega instantanea', platform: 'Overwatch 2', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g46', name: '200 Credits - Rocket League', description: 'Creditos para Rocket League. Compra items del shop, el Rocket Pass y blueprints.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/rocketleague.png', rating: 4.4, reviews: 2200, sold: 15000, deliveryTime: 'Entrega instantanea', platform: 'Rocket League', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g47', name: '11000 Credits - Rocket League', description: 'Paquete de 11000 creditos RL. Skins de coches premium, boosts y ruedas exclusivas.', price: 24.99, originalPrice: 49.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/rocketleague.png', rating: 4.5, reviews: 1800, sold: 12000, deliveryTime: 'Entrega instantanea', platform: 'Rocket League', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g48', name: '1000 Silver - Destiny 2', description: 'Plata para Destiny 2. Compra items de Eververse, skins de armas y adornos.', price: 4.99, originalPrice: 9.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/destiny2.png', rating: 4.3, reviews: 1600, sold: 10000, deliveryTime: 'Entrega instantanea', platform: 'Destiny 2', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'g49', name: 'FIFA Mobile Coins - 2M', description: '2 millones de monedas para FIFA Mobile. Construye tu equipo ultimate dream team.', price: 8.99, originalPrice: 19.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/fifamobile.png', rating: 4.4, reviews: 2800, sold: 18000, deliveryTime: '5-30 minutos', platform: 'FIFA Mobile', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'g50', name: 'Gemas Clash Royale - 5000', description: 'Paquete mega de 5000 gemas para Clash Royale. Maximo poder para tu arena.', price: 12.99, originalPrice: 34.99, category: 'gaming', subcategory: 'Monedas', image: '/products/gen/clashroyale.png', rating: 4.6, reviews: 4200, sold: 30000, deliveryTime: 'Entrega instantanea', platform: 'Clash Royale', region: 'Global', tags: ['oferta', 'popular'], stock: 999, featured: false },
// =========================================
// STREAMING (30 productos)
// =========================================
{ id: 's1', name: 'Netflix Premium - 1 Mes', description: 'Cuenta premium Netflix. Calidad 4K, 4 pantallas simultaneas y sin anuncios.', price: 3.99, originalPrice: 22.99, category: 'streaming', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.7, reviews: 15200, sold: 120000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 's2', name: 'Netflix Premium - 3 Meses', description: '3 meses de Netflix Premium full. Ahorra comprando el paquete trimestral.', price: 9.99, originalPrice: 68.97, category: 'streaming', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.8, reviews: 8900, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's3', name: 'Netflix Premium - 6 Meses', description: '6 meses de Netflix Premium. Serie completa sin interrupciones, maximo ahorro.', price: 16.99, originalPrice: 137.94, category: 'streaming', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.9, reviews: 6200, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 500, featured: false },
{ id: 's4', name: 'Netflix Premium - 1 Ano', description: '12 meses de Netflix Premium. El mejor precio anual con todos los beneficios premium.', price: 29.99, originalPrice: 275.88, category: 'streaming', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.9, reviews: 4200, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 300, featured: false },
{ id: 's5', name: 'Spotify Premium - 1 Mes', description: '1 mes de Spotify Premium. Sin anuncios, descarga ilimitada y calidad extrema.', price: 1.99, originalPrice: 4.99, category: 'streaming', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.8, reviews: 22300, sold: 210000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 's6', name: 'Spotify Premium - 3 Meses', description: '3 meses de Spotify Premium. Sin anuncios, descarga ilimitada, calidad maxima.', price: 4.99, originalPrice: 14.97, category: 'streaming', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.8, reviews: 18900, sold: 195000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 's7', name: 'Spotify Premium - 6 Meses', description: '6 meses de Spotify Premium al mejor precio. Musica sin limites por medio ano.', price: 8.99, originalPrice: 59.94, category: 'streaming', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.9, reviews: 11200, sold: 89000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 's8', name: 'Spotify Premium Duo - 3 Meses', description: '3 meses de Spotify Duo para 2 cuentas. Ideal para parejas o companeros de cuarto.', price: 7.49, originalPrice: 26.97, category: 'streaming', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.8, reviews: 5200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's9', name: 'Spotify Premium Family - 3 Meses', description: '3 meses de Spotify Family para hasta 6 cuentas. La mejor opcion para familias.', price: 9.99, originalPrice: 44.97, category: 'streaming', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.7, reviews: 4800, sold: 35000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's10', name: 'Disney+ Premium - 1 Mes', description: 'Marvel, Star Wars, Pixar, National Geographic y mas. Calidad 4K UHD HDR.', price: 3.49, originalPrice: 13.99, category: 'streaming', subcategory: 'Disney+', image: '/products/gen/disney.png', rating: 4.6, reviews: 8900, sold: 67000, deliveryTime: 'Entrega instantanea', platform: 'Disney+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's11', name: 'Disney+ Premium - 3 Meses', description: '3 meses de Disney+ Premium con todo el catalogo Marvel, Star Wars y Pixar en 4K.', price: 8.99, originalPrice: 41.97, category: 'streaming', subcategory: 'Disney+', image: '/products/gen/disney.png', rating: 4.7, reviews: 5200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Disney+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's12', name: 'Disney+ Premium - 6 Meses', description: '6 meses de Disney+ Premium. Medio ano de Marvel, Star Wars, Pixar y mas.', price: 14.99, originalPrice: 83.94, category: 'streaming', subcategory: 'Disney+', image: '/products/gen/disney.png', rating: 4.8, reviews: 3800, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'Disney+', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 's13', name: 'Crunchyroll Premium - 1 Mes', description: 'Anime sin anuncios, todos los titulos, estrenos simultaneos con Japon y manga incluido.', price: 2.99, originalPrice: 9.99, category: 'streaming', subcategory: 'Crunchyroll', image: '/products/gen/crunchyroll.png', rating: 4.5, reviews: 5400, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Crunchyroll', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's14', name: 'Crunchyroll Premium - 3 Meses', description: '3 meses de Crunchyroll Premium. Anime ilimitado sin anuncios con manga incluido.', price: 6.99, originalPrice: 29.97, category: 'streaming', subcategory: 'Crunchyroll', image: '/products/gen/crunchyroll.png', rating: 4.6, reviews: 3800, sold: 26000, deliveryTime: 'Entrega instantanea', platform: 'Crunchyroll', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's15', name: 'Max (HBO) - 1 Mes', description: 'Series de HBO, peliculas Warner Bros, contenido DC y documentales exclusivos en 4K.', price: 3.49, originalPrice: 15.49, category: 'streaming', subcategory: 'Max', image: '/products/gen/hbomax.png', rating: 4.5, reviews: 6200, sold: 42000, deliveryTime: 'Entrega instantanea', platform: 'Max', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's16', name: 'Max (HBO) - 3 Meses', description: '3 meses de Max con todo el catalogo HBO. Game of Thrones, Succession y mas.', price: 8.99, originalPrice: 46.47, category: 'streaming', subcategory: 'Max', image: '/products/gen/hbomax.png', rating: 4.6, reviews: 4200, sold: 30000, deliveryTime: 'Entrega instantanea', platform: 'Max', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's17', name: 'Amazon Prime Video - 1 Mes', description: 'Peliculas, series originales de Amazon, deportes en vivo y envios Prime incluidos.', price: 3.99, originalPrice: 14.99, category: 'streaming', subcategory: 'Amazon Prime', image: '/products/gen/amazonprime.png', rating: 4.6, reviews: 7800, sold: 56000, deliveryTime: 'Entrega instantanea', platform: 'Amazon Prime', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's18', name: 'Amazon Prime Video - 6 Meses', description: '6 meses de Prime Video. Series originales, peliculas, deportes y envios gratis.', price: 19.99, originalPrice: 89.94, category: 'streaming', subcategory: 'Amazon Prime', image: '/products/gen/amazonprime.png', rating: 4.7, reviews: 4200, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'Amazon Prime', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's19', name: 'Paramount+ - 1 Mes', description: 'Contenido de CBS, MTV, Nickelodeon, peliculas de Paramount y series exclusivas.', price: 2.49, originalPrice: 11.99, category: 'streaming', subcategory: 'Paramount+', image: '/products/gen/paramount.png', rating: 4.3, reviews: 3200, sold: 24000, deliveryTime: 'Entrega instantanea', platform: 'Paramount+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's20', name: 'Apple TV+ - 1 Mes', description: 'Series originales galardonadas de Apple, peliculas exclusivas y documentales.', price: 2.99, originalPrice: 9.99, category: 'streaming', subcategory: 'Apple TV+', image: '/products/gen/appletv.png', rating: 4.4, reviews: 4100, sold: 29000, deliveryTime: 'Entrega instantanea', platform: 'Apple TV+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's21', name: 'Hulu - 1 Mes', description: 'Series, peliculas y contenido original de Hulu. Next-day TV y exclusivos.', price: 2.99, originalPrice: 14.99, category: 'streaming', subcategory: 'Hulu', image: '/products/gen/gaming-cat.png', rating: 4.4, reviews: 4800, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Hulu', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's22', name: 'Hulu + Live TV - 1 Mes', description: 'Hulu con TV en vivo. Mas de 95 canales, deportes en vivo y DVR ilimitado.', price: 9.99, originalPrice: 69.99, category: 'streaming', subcategory: 'Hulu', image: '/products/gen/gaming-cat.png', rating: 4.5, reviews: 2800, sold: 18000, deliveryTime: 'Entrega instantanea', platform: 'Hulu', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 's23', name: 'Peacock Premium - 3 Meses', description: 'NBC Universal, deportes Premier League, WWE y peliculas en streaming.', price: 4.99, originalPrice: 29.97, category: 'streaming', subcategory: 'Peacock', image: '/products/gen/gaming-cat.png', rating: 4.3, reviews: 2200, sold: 15000, deliveryTime: 'Entrega instantanea', platform: 'Peacock', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's24', name: 'DAZN - 1 Mes', description: 'Deportes en vivo: futbol, boxeo, MMA y mas. Transmisiones exclusivas en HD.', price: 3.99, originalPrice: 14.99, category: 'streaming', subcategory: 'DAZN', image: '/products/gen/gaming-cat.png', rating: 4.4, reviews: 3200, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'DAZN', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 's25', name: 'Star+ - 1 Mes', description: 'Star+, ESPN y contenido de Disney no disponible en Disney+. Deportes y series.', price: 2.99, originalPrice: 10.99, category: 'streaming', subcategory: 'Star+', image: '/products/gen/gaming-cat.png', rating: 4.3, reviews: 2800, sold: 20000, deliveryTime: 'Entrega instantanea', platform: 'Star+', region: 'Latam', tags: ['oferta'], stock: 999, featured: false },
{ id: 's26', name: 'Star+ - 6 Meses', description: '6 meses de Star+ con ESPN y todo el contenido exclusivo de Star para Latinoamerica.', price: 12.99, originalPrice: 65.94, category: 'streaming', subcategory: 'Star+', image: '/products/gen/gaming-cat.png', rating: 4.4, reviews: 1800, sold: 12000, deliveryTime: 'Entrega instantanea', platform: 'Star+', region: 'Latam', tags: ['oferta'], stock: 500, featured: false },
{ id: 's27', name: 'Crunchyroll Mega Fan - 1 Ano', description: '12 meses de Crunchyroll Mega Fan. Anime sin anuncios, 6 pantallas y offline viewing.', price: 24.99, originalPrice: 119.88, category: 'streaming', subcategory: 'Crunchyroll', image: '/products/gen/crunchyroll.png', rating: 4.8, reviews: 3200, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Crunchyroll', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 500, featured: false },
{ id: 's28', name: 'Disney+ Bundle (Disney+ + Hulu + Max) - 1 Mes', description: 'El bundle completo de Disney: Disney+, Hulu y Max juntos por un precio unico.', price: 5.99, originalPrice: 29.99, category: 'streaming', subcategory: 'Disney+', image: '/products/gen/disney.png', rating: 4.7, reviews: 5200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Disney+', region: 'US', tags: ['oferta', 'tendencia'], stock: 999, featured: false },
{ id: 's29', name: 'Paramount+ - 6 Meses', description: '6 meses de Paramount+ con contenido de CBS, MTV, Nickelodeon y series exclusivas.', price: 11.99, originalPrice: 71.94, category: 'streaming', subcategory: 'Paramount+', image: '/products/gen/paramount.png', rating: 4.4, reviews: 2200, sold: 15000, deliveryTime: 'Entrega instantanea', platform: 'Paramount+', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 's30', name: 'Apple TV+ - 3 Meses', description: '3 meses de Apple TV+. Series galardonadas como Ted Lasso, Severance y The Morning Show.', price: 6.99, originalPrice: 29.97, category: 'streaming', subcategory: 'Apple TV+', image: '/products/gen/appletv.png', rating: 4.5, reviews: 3200, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Apple TV+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
// =========================================
// CUENTAS (15 productos)
// =========================================
{ id: 'a1', name: 'Cuenta Netflix Premium - 6 Meses Garantia', description: 'Cuenta compartida Netflix Premium con garantia de 6 meses. 4K, sin anuncios.', price: 8.99, originalPrice: 47.94, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/netflix.png', rating: 4.6, reviews: 8500, sold: 68000, deliveryTime: '5-30 minutos', platform: 'Netflix', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 'a2', name: 'Cuenta Netflix Premium - 12 Meses Garantia', description: 'Cuenta compartida Netflix con garantia total de 12 meses. Cambios sin costo.', price: 14.99, originalPrice: 95.88, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/netflix.png', rating: 4.7, reviews: 6200, sold: 45000, deliveryTime: '5-30 minutos', platform: 'Netflix', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 500, featured: false },
{ id: 'a3', name: 'Cuenta Spotify Premium - 6 Meses', description: 'Cuenta Spotify Premium con garantia de 6 meses. Sin anuncios, descarga ilimitada.', price: 5.99, originalPrice: 35.94, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/spotify.png', rating: 4.7, reviews: 9200, sold: 72000, deliveryTime: '5-30 minutos', platform: 'Spotify', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: false },
{ id: 'a4', name: 'Cuenta Spotify Premium - 12 Meses', description: 'Cuenta Spotify Premium con garantia de 12 meses. Musica sin limites por un ano.', price: 9.99, originalPrice: 71.88, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/spotify.png', rating: 4.8, reviews: 6800, sold: 52000, deliveryTime: '5-30 minutos', platform: 'Spotify', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'a5', name: 'Cuenta Disney+ Premium - 6 Meses', description: 'Cuenta Disney+ Premium compartida con 6 meses de garantia. Marvel y Star Wars en 4K.', price: 7.99, originalPrice: 53.94, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/disney.png', rating: 4.5, reviews: 5800, sold: 38000, deliveryTime: '5-30 minutos', platform: 'Disney+', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'a6', name: 'Cuenta Crunchyroll Premium - 6 Meses', description: 'Cuenta Crunchyroll con garantia de 6 meses. Anime ilimitado sin anuncios.', price: 6.99, originalPrice: 35.94, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/crunchyroll.png', rating: 4.4, reviews: 4200, sold: 28000, deliveryTime: '5-30 minutos', platform: 'Crunchyroll', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'a7', name: 'Cuenta Fortnite - Skins Exclusivas', description: 'Cuenta de Fortnite con mas de 50 skins exclusivas, pases de batalla pasados y emotes.', price: 9.99, originalPrice: 149.99, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/fortnite.png', rating: 4.5, reviews: 4800, sold: 32000, deliveryTime: '1-6 horas', platform: 'Fortnite', region: 'Global', tags: ['oferta', 'premium'], stock: 100, featured: false },
{ id: 'a8', name: 'Cuenta Minecraft Java Premium', description: 'Cuenta premium Minecraft Java Edition original. Acceso a multijugador, skins y servidores.', price: 4.99, originalPrice: 26.95, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/minecraft.png', rating: 4.4, reviews: 7200, sold: 55000, deliveryTime: '1-24 horas', platform: 'Minecraft', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 150, featured: true },
{ id: 'a9', name: 'Cuenta Roblox Premium - 12 Meses', description: 'Cuenta Roblox con membresia Premium activa por 12 meses. Robux mensuales incluidos.', price: 14.99, originalPrice: 59.99, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/roblox.png', rating: 4.5, reviews: 3800, sold: 24000, deliveryTime: '1-6 horas', platform: 'Roblox', region: 'Global', tags: ['oferta'], stock: 150, featured: false },
{ id: 'a10', name: 'Cuenta Valorant - 50+ Skins', description: 'Cuenta de Valorant con mas de 50 skins desbloqueadas incluyendo ediciones premium.', price: 12.99, originalPrice: 199.99, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/valorant.png', rating: 4.6, reviews: 3200, sold: 18000, deliveryTime: '1-6 horas', platform: 'Valorant', region: 'Global', tags: ['oferta', 'premium'], stock: 100, featured: false },
{ id: 'a11', name: 'Cuenta Genshin Impact - AR55+', description: 'Cuenta de Genshin Impact con Adventure Rank 55+, personajes 5 estrellas y armas.', price: 14.99, originalPrice: 249.99, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/genshin.png', rating: 4.7, reviews: 4200, sold: 22000, deliveryTime: '1-6 horas', platform: 'Genshin Impact', region: 'Global', tags: ['oferta', 'premium'], stock: 80, featured: false },
{ id: 'a12', name: 'Cuenta Max (HBO) - 6 Meses Garantia', description: 'Cuenta compartida de Max con 6 meses de garantia. Todo el catalogo HBO.', price: 7.99, originalPrice: 46.47, category: 'accounts', subcategory: 'Streaming', image: '/products/gen/hbomax.png', rating: 4.5, reviews: 3800, sold: 26000, deliveryTime: '5-30 minutos', platform: 'HBO Max', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'a13', name: 'Cuenta Instagram Verificada', description: 'Cuenta de Instagram con verification badge. Lista para uso inmediato con seguidores reales.', price: 19.99, originalPrice: 99.99, category: 'accounts', subcategory: 'Redes Sociales', image: '/products/gen/gaming-cat.png', rating: 4.2, reviews: 1800, sold: 8500, deliveryTime: '1-24 horas', platform: 'Social', region: 'Global', tags: ['premium'], stock: 50, featured: false },
{ id: 'a14', name: 'Cuenta TikTok con Seguidores', description: 'Cuenta de TikTok con seguidores reales y engagement organico. Ideal para creadores.', price: 14.99, originalPrice: 79.99, category: 'accounts', subcategory: 'Redes Sociales', image: '/products/gen/gaming-cat.png', rating: 4.3, reviews: 2200, sold: 12000, deliveryTime: '1-24 horas', platform: 'Social', region: 'Global', tags: ['tendencia'], stock: 80, featured: false },
{ id: 'a15', name: 'Cuenta Discord Nitro - 12 Meses', description: 'Cuenta Discord con Nitro activo por 12 meses. Emojis, boosts y HD streaming.', price: 9.99, originalPrice: 99.99, category: 'accounts', subcategory: 'Gaming', image: '/products/gen/gaming-cat.png', rating: 4.6, reviews: 3200, sold: 18000, deliveryTime: '1-6 horas', platform: 'Discord', region: 'Global', tags: ['oferta'], stock: 200, featured: false },
// =========================================
// GIFT CARDS (25 productos)
// =========================================
{ id: 'gc1', name: 'Tarjeta Steam - $10 USD', description: 'Gift card Steam de $10. Perfecta para juegos indie o DLCs economicos.', price: 9.49, originalPrice: 10.00, category: 'giftcards', subcategory: 'Steam', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 22000, sold: 195000, deliveryTime: 'Entrega instantanea', platform: 'Steam', region: 'Global', tags: ['mas vendido'], stock: 999, featured: false },
{ id: 'gc2', name: 'Tarjeta Steam - $20 USD', description: 'Gift card Steam de $20. Perfecta para comprar juegos indie o en oferta.', price: 18.99, originalPrice: 20.00, category: 'giftcards', subcategory: 'Steam', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 18000, sold: 156000, deliveryTime: 'Entrega instantanea', platform: 'Steam', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc3', name: 'Tarjeta Steam - $50 USD', description: 'Gift card Steam. Compra juegos, DLC, software y mas en la tienda mas grande de PC.', price: 46.99, originalPrice: 50.00, category: 'giftcards', subcategory: 'Steam', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 22000, sold: 185000, deliveryTime: 'Entrega instantanea', platform: 'Steam', region: 'Global', tags: ['mas vendido'], stock: 999, featured: true },
{ id: 'gc4', name: 'Tarjeta Steam - $100 USD', description: 'Gift card Steam de $100. Ideal para comprar multiples juegos AAA en oferta.', price: 93.99, originalPrice: 100.00, category: 'giftcards', subcategory: 'Steam', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 9800, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'Steam', region: 'Global', tags: ['popular'], stock: 500, featured: false },
{ id: 'gc5', name: 'Tarjeta PlayStation - $10 USD', description: 'Gift card PlayStation Store para PS4/PS5. Juegos, DLC y suscripciones.', price: 9.49, originalPrice: 10.00, category: 'giftcards', subcategory: 'PlayStation', image: '/products/gen/gaming-cat.png', rating: 4.7, reviews: 12000, sold: 98000, deliveryTime: 'Entrega instantanea', platform: 'PlayStation', region: 'Americas', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc6', name: 'Tarjeta PlayStation - $25 USD', description: 'Gift card PlayStation Store para PS4/PS5. Juegos, DLC y suscripciones.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'PlayStation', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 16500, sold: 142000, deliveryTime: 'Entrega instantanea', platform: 'PlayStation', region: 'Americas', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc7', name: 'Tarjeta PlayStation - $50 USD', description: 'Gift card PlayStation Store de $50. Ideal para juegos AAA de lanzamiento.', price: 46.49, originalPrice: 50.00, category: 'giftcards', subcategory: 'PlayStation', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 12400, sold: 98000, deliveryTime: 'Entrega instantanea', platform: 'PlayStation', region: 'Americas', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'gc8', name: 'Tarjeta Xbox - $15 USD', description: 'Gift card Xbox para Xbox Store y Game Pass. Juegos y suscripciones.', price: 14.49, originalPrice: 15.00, category: 'giftcards', subcategory: 'Xbox', image: '/products/gen/gaming-cat.png', rating: 4.7, reviews: 8200, sold: 65000, deliveryTime: 'Entrega instantanea', platform: 'Xbox', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc9', name: 'Tarjeta Xbox - $25 USD', description: 'Gift card Xbox de $25. Perfecta para meses de Game Pass o juegos indie.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Xbox', image: '/products/gen/gaming-cat.png', rating: 4.7, reviews: 9800, sold: 78000, deliveryTime: 'Entrega instantanea', platform: 'Xbox', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc10', name: 'Tarjeta Xbox - $50 USD', description: 'Gift card Xbox para Xbox Store y Game Pass. Juegos y suscripciones.', price: 45.99, originalPrice: 50.00, category: 'giftcards', subcategory: 'Xbox', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 9800, sold: 78000, deliveryTime: 'Entrega instantanea', platform: 'Xbox', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc11', name: 'Tarjeta Google Play - $10 USD', description: 'Gift card Google Play para apps, juegos y libros en Android.', price: 9.49, originalPrice: 10.00, category: 'giftcards', subcategory: 'Google Play', image: '/products/gen/gaming-cat.png', rating: 4.6, reviews: 8800, sold: 68000, deliveryTime: 'Entrega instantanea', platform: 'Google Play', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc12', name: 'Tarjeta Google Play - $25 USD', description: 'Gift card Google Play para apps, juegos, peliculas y libros en Android.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Google Play', image: '/products/gen/gaming-cat.png', rating: 4.6, reviews: 11200, sold: 95000, deliveryTime: 'Entrega instantanea', platform: 'Google Play', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc13', name: 'Tarjeta Apple/iTunes - $25 USD', description: 'Gift card Apple para App Store, iTunes, Apple Music y iCloud.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Apple', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 14200, sold: 118000, deliveryTime: 'Entrega instantanea', platform: 'Apple', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc14', name: 'Tarjeta Apple/iTunes - $50 USD', description: 'Gift card Apple de $50 para App Store, iTunes, Apple Music y iCloud.', price: 46.99, originalPrice: 50.00, category: 'giftcards', subcategory: 'Apple', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 10500, sold: 88000, deliveryTime: 'Entrega instantanea', platform: 'Apple', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc15', name: 'Tarjeta Amazon - $25 USD', description: 'Gift card Amazon para compras en cualquier categoria de la tienda.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Amazon', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 15000, sold: 128000, deliveryTime: 'Entrega instantanea', platform: 'Amazon', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc16', name: 'Tarjeta Amazon - $50 USD', description: 'Gift card Amazon para compras en cualquier categoria de la tienda.', price: 47.49, originalPrice: 50.00, category: 'giftcards', subcategory: 'Amazon', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 19500, sold: 168000, deliveryTime: 'Entrega instantanea', platform: 'Amazon', region: 'Global', tags: ['mas vendido'], stock: 999, featured: false },
{ id: 'gc17', name: 'Tarjeta Netflix - $15 USD', description: 'Gift card oficial de Netflix. Carga saldo a tu cuenta de Netflix.', price: 14.49, originalPrice: 15.00, category: 'giftcards', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.7, reviews: 6200, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Americas', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc18', name: 'Tarjeta Netflix - $30 USD', description: 'Gift card oficial de Netflix. Carga saldo a tu cuenta de Netflix.', price: 28.49, originalPrice: 30.00, category: 'giftcards', subcategory: 'Netflix', image: '/products/gen/netflix.png', rating: 4.7, reviews: 8900, sold: 67000, deliveryTime: 'Entrega instantanea', platform: 'Netflix', region: 'Americas', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc19', name: 'Tarjeta Epic Games - $10 USD', description: 'Gift card Epic Games Store para juegos exclusivos y gratis.', price: 9.49, originalPrice: 10.00, category: 'giftcards', subcategory: 'Epic Games', image: '/products/gen/gaming-cat.png', rating: 4.5, reviews: 4800, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'Epic Games', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc20', name: 'Tarjeta Epic Games - $25 USD', description: 'Gift card Epic Games Store. Compra juegos exclusivos y de gran presupuesto.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Epic Games', image: '/products/gen/gaming-cat.png', rating: 4.6, reviews: 5800, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Epic Games', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc21', name: 'Tarjeta Roblox - $10 USD', description: 'Gift card Roblox oficial. Canjea por Robux en la tienda de Roblox.', price: 9.49, originalPrice: 10.00, category: 'giftcards', subcategory: 'Roblox', image: '/products/gen/roblox.png', rating: 4.7, reviews: 11000, sold: 85000, deliveryTime: 'Entrega instantanea', platform: 'Roblox', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc22', name: 'Tarjeta Roblox - $25 USD', description: 'Gift card Roblox oficial. Canjea por Robux y compra items, game passes premium.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Roblox', image: '/products/gen/roblox.png', rating: 4.8, reviews: 14200, sold: 115000, deliveryTime: 'Entrega instantanea', platform: 'Roblox', region: 'Global', tags: ['mas vendido', 'popular'], stock: 999, featured: true },
{ id: 'gc23', name: 'Tarjeta Spotify - $15 USD', description: 'Gift card Spotify. Carga saldo para meses de Spotify Premium sin anuncios.', price: 14.49, originalPrice: 15.00, category: 'giftcards', subcategory: 'Spotify', image: '/products/gen/spotify.png', rating: 4.6, reviews: 7200, sold: 52000, deliveryTime: 'Entrega instantanea', platform: 'Spotify', region: 'Global', tags: ['popular'], stock: 999, featured: false },
{ id: 'gc24', name: 'Tarjeta Nintendo eShop - $25 USD', description: 'Gift card Nintendo eShop para juegos de Switch y clasicos.', price: 23.49, originalPrice: 25.00, category: 'giftcards', subcategory: 'Nintendo', image: '/products/gen/gaming-cat.png', rating: 4.7, reviews: 6200, sold: 42000, deliveryTime: 'Entrega instantanea', platform: 'Nintendo', region: 'Americas', tags: ['oferta'], stock: 999, featured: false },
{ id: 'gc25', name: 'Tarjeta Nintendo eShop - $50 USD', description: 'Gift card Nintendo eShop de $50. Juegos de Switch, DLC y clasicos NES/SNES.', price: 46.99, originalPrice: 50.00, category: 'giftcards', subcategory: 'Nintendo', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 8200, sold: 62000, deliveryTime: 'Entrega instantanea', platform: 'Nintendo', region: 'Americas', tags: ['popular', 'oferta'], stock: 999, featured: false },
// =========================================
// SOFTWARE (20 productos)
// =========================================
{ id: 'sw1', name: 'Licencia Windows 11 Pro - Clave Digital', description: 'Licencia original Windows 11 Pro. Clave 32/64 bits, activacion online oficial Microsoft.', price: 8.99, originalPrice: 199.99, category: 'software', subcategory: 'Licencias Windows', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 28500, sold: 245000, deliveryTime: 'Entrega instantanea', platform: 'Windows', region: 'Global', tags: ['mas vendido', 'oferta', 'mejor margen'], stock: 999, featured: true },
{ id: 'sw2', name: 'Licencia Windows 10 Pro - Clave Digital', description: 'Licencia original Windows 10 Pro. Perfecta para PCs que no soportan Windows 11.', price: 6.99, originalPrice: 139.99, category: 'software', subcategory: 'Licencias Windows', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 16400, sold: 142000, deliveryTime: 'Entrega instantanea', platform: 'Windows', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 999, featured: false },
{ id: 'sw3', name: 'Licencia Windows 11 Home - Clave Digital', description: 'Licencia Windows 11 Home para uso personal. Clave oficial de Microsoft.', price: 5.99, originalPrice: 129.99, category: 'software', subcategory: 'Licencias Windows', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 12200, sold: 98000, deliveryTime: 'Entrega instantanea', platform: 'Windows', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw4', name: 'Microsoft Office 2024 Professional', description: 'Office 2024 Pro completo: Word, Excel, PowerPoint, Outlook, Access. Licencia perpetua 1 PC.', price: 12.49, originalPrice: 249.99, category: 'software', subcategory: 'Office', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 19800, sold: 178000, deliveryTime: 'Entrega instantanea', platform: 'Microsoft', region: 'Global', tags: ['mas vendido', 'oferta', 'mejor margen'], stock: 999, featured: true },
{ id: 'sw5', name: 'Microsoft Office 2024 Home & Student', description: 'Office 2024 Home: Word, Excel, PowerPoint. Licencia perpetua para uso no comercial.', price: 9.99, originalPrice: 149.99, category: 'software', subcategory: 'Office', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 14200, sold: 120000, deliveryTime: 'Entrega instantanea', platform: 'Microsoft', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 999, featured: false },
{ id: 'sw6', name: 'Microsoft Office 365 - 1 Ano (2 PCs)', description: 'Suscripcion Office 365 por 1 ano para 2 computadoras. Siempre con la ultima version.', price: 14.99, originalPrice: 99.99, category: 'software', subcategory: 'Office', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 8500, sold: 62000, deliveryTime: 'Entrega instantanea', platform: 'Microsoft', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw7', name: 'Adobe Creative Cloud - 1 Ano', description: 'Suite completa Adobe: Photoshop, Illustrator, Premiere Pro, After Effects y mas.', price: 34.99, originalPrice: 659.88, category: 'software', subcategory: 'Herramientas', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 8900, sold: 52000, deliveryTime: 'Entrega instantanea', platform: 'Adobe', region: 'Global', tags: ['mejor margen', 'oferta'], stock: 999, featured: true },
{ id: 'sw8', name: 'Adobe Photoshop 2024 - Licencia Perpetua', description: 'Photoshop 2024 licencia completa. Edicion profesional de imagenes y diseno grafico.', price: 19.99, originalPrice: 299.99, category: 'software', subcategory: 'Herramientas', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 6200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Adobe', region: 'Global', tags: ['oferta'], stock: 500, featured: false },
{ id: 'sw9', name: 'NordVPN - 2 Anos', description: 'VPN premium 2 anos. 5500+ servidores en 60 paises, sin registros, velocidad maxima.', price: 29.99, originalPrice: 286.56, category: 'software', subcategory: 'VPN', image: '/products/gen/software-cat.png', rating: 4.8, reviews: 14200, sold: 98000, deliveryTime: 'Entrega instantanea', platform: 'VPN', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 999, featured: false },
{ id: 'sw10', name: 'NordVPN - 1 Ano', description: 'VPN premium 1 ano. 5500+ servidores, sin registros, kill switch y split tunneling.', price: 18.99, originalPrice: 143.28, category: 'software', subcategory: 'VPN', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 11800, sold: 82000, deliveryTime: 'Entrega instantanea', platform: 'VPN', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw11', name: 'ExpressVPN - 1 Ano', description: 'ExpressVPN 1 ano. Servidores en 94 paises, velocidad ultrarrapida, split tunneling.', price: 24.99, originalPrice: 155.88, category: 'software', subcategory: 'VPN', image: '/products/gen/software-cat.png', rating: 4.8, reviews: 10500, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'VPN', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw12', name: 'Kaspersky Total Security - 1 Ano 3 PCs', description: 'Proteccion completa Kaspersky para 3 dispositivos: antivirus, firewall, VPN y control parental.', price: 9.99, originalPrice: 49.99, category: 'software', subcategory: 'Antivirus', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 8200, sold: 58000, deliveryTime: 'Entrega instantanea', platform: 'Antivirus', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw13', name: 'Bitdefender Premium Security - 1 Ano 5 PCs', description: 'Bitdefender para 5 dispositivos. Antivirus, VPN, anti-phishing y optimizacion.', price: 12.99, originalPrice: 89.99, category: 'software', subcategory: 'Antivirus', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 7200, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Antivirus', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw14', name: 'Norton 360 Deluxe - 1 Ano 3 PCs', description: 'Norton 360 Deluxe: antivirus, VPN, cloud backup 50GB y password manager para 3 PCs.', price: 11.99, originalPrice: 84.99, category: 'software', subcategory: 'Antivirus', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 9500, sold: 62000, deliveryTime: 'Entrega instantanea', platform: 'Antivirus', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw15', name: 'Malwarebytes Premium - 1 Ano 3 PCs', description: 'Malwarebytes para 3 dispositivos. Proteccion contra malware, ransomware y phishing.', price: 8.99, originalPrice: 44.99, category: 'software', subcategory: 'Antivirus', image: '/products/gen/software-cat.png', rating: 4.5, reviews: 6800, sold: 45000, deliveryTime: 'Entrega instantanea', platform: 'Antivirus', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw16', name: 'Avast Premium Security - 1 Ano 1 PC', description: 'Avast Premium: antivirus, firewall, anti-spam y sandbox para archivos sospechosos.', price: 6.99, originalPrice: 39.99, category: 'software', subcategory: 'Antivirus', image: '/products/gen/software-cat.png', rating: 4.4, reviews: 7600, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Antivirus', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw17', name: 'Windows 10/11 Pro Pack - 2 Licencias', description: 'Paquete de 2 licencias Windows Pro (10 u 11). Ideal para equipos personales o pequenas empresas.', price: 14.99, originalPrice: 399.98, category: 'software', subcategory: 'Licencias Windows', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 8500, sold: 52000, deliveryTime: 'Entrega instantanea', platform: 'Windows', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 500, featured: false },
{ id: 'sw18', name: 'Microsoft Office 2021 Professional', description: 'Office 2021 Pro: Word, Excel, PowerPoint, Outlook, Publisher. Licencia perpetua clasica.', price: 10.99, originalPrice: 249.99, category: 'software', subcategory: 'Office', image: '/products/gen/software-cat.png', rating: 4.5, reviews: 12000, sold: 95000, deliveryTime: 'Entrega instantanea', platform: 'Microsoft', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 999, featured: false },
{ id: 'sw19', name: 'Surfshark VPN - 2 Anos', description: 'Surfshark VPN 2 anos. Conexiones ilimitadas, kill switch y alertas de filtracion de datos.', price: 19.99, originalPrice: 191.76, category: 'software', subcategory: 'VPN', image: '/products/gen/software-cat.png', rating: 4.7, reviews: 8200, sold: 56000, deliveryTime: 'Entrega instantanea', platform: 'VPN', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sw20', name: 'CyberGhost VPN - 2 Anos', description: 'CyberGhost VPN 2 anos. 11000+ servidores, dedicado streaming y NoSpy servers.', price: 22.99, originalPrice: 191.64, category: 'software', subcategory: 'VPN', image: '/products/gen/software-cat.png', rating: 4.6, reviews: 6800, sold: 42000, deliveryTime: 'Entrega instantanea', platform: 'VPN', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
// =========================================
// SUSCRIPCIONES (20 productos)
// =========================================
{ id: 'sub1', name: 'YouTube Premium - 1 Mes', description: 'Sin anuncios, descarga de videos, YouTube Music Premium y reproduccion en segundo plano.', price: 2.49, originalPrice: 5.99, category: 'subscriptions', subcategory: 'YouTube Premium', image: '/products/gen/subscriptions-cat.png', rating: 4.7, reviews: 8600, sold: 65000, deliveryTime: 'Entrega instantanea', platform: 'YouTube', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'sub2', name: 'YouTube Premium - 3 Meses', description: 'Sin anuncios, descarga de videos, YouTube Music Premium y reproduccion en segundo plano.', price: 5.99, originalPrice: 17.97, category: 'subscriptions', subcategory: 'YouTube Premium', image: '/products/gen/subscriptions-cat.png', rating: 4.7, reviews: 13600, sold: 112000, deliveryTime: 'Entrega instantanea', platform: 'YouTube', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: true },
{ id: 'sub3', name: 'YouTube Premium - 6 Meses', description: '6 meses de YouTube Premium sin anuncios, con descarga y YouTube Music incluido.', price: 9.99, originalPrice: 35.94, category: 'subscriptions', subcategory: 'YouTube Premium', image: '/products/gen/subscriptions-cat.png', rating: 4.8, reviews: 7200, sold: 58000, deliveryTime: 'Entrega instantanea', platform: 'YouTube', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub4', name: 'Discord Nitro - 1 Mes', description: 'Emojis personalizados, stickers globales, streaming HD, mejor calidad de voz y boost.', price: 2.99, originalPrice: 9.99, category: 'subscriptions', subcategory: 'Discord Nitro', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 6500, sold: 48000, deliveryTime: 'Entrega instantanea', platform: 'Discord', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub5', name: 'Discord Nitro - 3 Meses', description: '3 meses de Discord Nitro. Emojis, stickers globales, streaming HD y 2 server boosts.', price: 6.99, originalPrice: 29.97, category: 'subscriptions', subcategory: 'Discord Nitro', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 8900, sold: 68000, deliveryTime: 'Entrega instantanea', platform: 'Discord', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub6', name: 'Discord Nitro - 12 Meses', description: '12 meses de Nitro. El mejor precio anual con todos los beneficios premium completos.', price: 19.99, originalPrice: 99.99, category: 'subscriptions', subcategory: 'Discord Nitro', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 5200, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Discord', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 500, featured: false },
{ id: 'sub7', name: 'Xbox Game Pass Ultimate - 1 Mes', description: 'Cientos de juegos para consola, PC y cloud gaming. Incluye EA Play y day-one releases.', price: 4.99, originalPrice: 16.99, category: 'subscriptions', subcategory: 'Cloud Gaming', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 16400, sold: 135000, deliveryTime: 'Entrega instantanea', platform: 'Xbox', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 'sub8', name: 'Xbox Game Pass Ultimate - 3 Meses', description: '3 meses de Game Pass Ultimate: consola + PC + cloud. La mejor oferta para gamers.', price: 12.99, originalPrice: 50.97, category: 'subscriptions', subcategory: 'Cloud Gaming', image: '/products/gen/gaming-cat.png', rating: 4.9, reviews: 9800, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'Xbox', region: 'Global', tags: ['oferta', 'tendencia'], stock: 999, featured: false },
{ id: 'sub9', name: 'Twitch Turbo - 1 Mes', description: 'Sin anuncios en Twitch, chat sin limite de emotes, color personalizado y almacenamiento extra.', price: 2.49, originalPrice: 8.99, category: 'subscriptions', subcategory: 'Twitch', image: '/products/gen/gaming-cat.png', rating: 4.5, reviews: 4200, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'Twitch', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub10', name: 'Twitch Turbo - 3 Meses', description: '3 meses de Twitch Turbo. Sin anuncios, emotes personalizados y almacenamiento extra.', price: 5.99, originalPrice: 26.97, category: 'subscriptions', subcategory: 'Twitch', image: '/products/gen/gaming-cat.png', rating: 4.5, reviews: 3200, sold: 22000, deliveryTime: 'Entrega instantanea', platform: 'Twitch', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub11', name: 'Canva Pro - 1 Ano', description: 'Diseno grafico profesional: plantillas premium, IA generativa, fondos removidos y 100M+ elementos.', price: 19.99, originalPrice: 119.99, category: 'subscriptions', subcategory: 'Canva Pro', image: '/products/gen/subscriptions-cat.png', rating: 4.7, reviews: 6800, sold: 42000, deliveryTime: 'Entrega instantanea', platform: 'Canva', region: 'Global', tags: ['oferta', 'mejor margen'], stock: 999, featured: true },
{ id: 'sub12', name: 'Canva Pro - 6 Meses', description: '6 meses de Canva Pro. Todo el poder de diseno con IA y plantillas premium.', price: 12.99, originalPrice: 59.94, category: 'subscriptions', subcategory: 'Canva Pro', image: '/products/gen/subscriptions-cat.png', rating: 4.6, reviews: 4200, sold: 28000, deliveryTime: 'Entrega instantanea', platform: 'Canva', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub13', name: 'PlayStation Plus Premium - 1 Mes', description: 'PS Plus Premium: juegos de catalogo, cloud streaming, ofertas y trials de juegos AAA.', price: 4.99, originalPrice: 17.99, category: 'subscriptions', subcategory: 'PlayStation Plus', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 9200, sold: 72000, deliveryTime: 'Entrega instantanea', platform: 'PlayStation', region: 'Global', tags: ['popular', 'oferta'], stock: 999, featured: false },
{ id: 'sub14', name: 'PlayStation Plus Premium - 1 Ano', description: '12 meses de PS Plus Premium. Juegos de catalogo, cloud streaming y ofertas exclusivas.', price: 29.99, originalPrice: 159.99, category: 'subscriptions', subcategory: 'PlayStation Plus', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 11200, sold: 85000, deliveryTime: 'Entrega instantanea', platform: 'PlayStation', region: 'Global', tags: ['mas vendido', 'oferta'], stock: 999, featured: true },
{ id: 'sub15', name: 'EA Play Pro - 1 Mes', description: 'Acceso a los mejores juegos de EA: FC 25, Battlefield y mas. Ediciones premium incluidas.', price: 3.99, originalPrice: 14.99, category: 'subscriptions', subcategory: 'EA Play', image: '/products/gen/subscriptions-cat.png', rating: 4.6, reviews: 5600, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'EA', region: 'Global', tags: ['oferta', 'tendencia'], stock: 999, featured: false },
{ id: 'sub16', name: 'EA Play Pro - 3 Meses', description: '3 meses de EA Play Pro. Juegos de EA con day-one access y ediciones premium.', price: 9.99, originalPrice: 44.97, category: 'subscriptions', subcategory: 'EA Play', image: '/products/gen/subscriptions-cat.png', rating: 4.6, reviews: 3800, sold: 24000, deliveryTime: 'Entrega instantanea', platform: 'EA', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub17', name: 'Nintendo Switch Online - 1 Ano', description: '12 meses de Nintendo Switch Online. Juegos retro, multijugador online y cloud saves.', price: 7.99, originalPrice: 19.99, category: 'subscriptions', subcategory: 'Cloud Gaming', image: '/products/gen/gaming-cat.png', rating: 4.7, reviews: 8200, sold: 62000, deliveryTime: 'Entrega instantanea', platform: 'Nintendo', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub18', name: 'Nintendo Switch Online + Expansion Pack - 1 Ano', description: '12 meses NSO con Expansion Pack: N64, GBA, Sega Genesis y DLCs de juegos Switch.', price: 14.99, originalPrice: 49.99, category: 'subscriptions', subcategory: 'Cloud Gaming', image: '/products/gen/gaming-cat.png', rating: 4.8, reviews: 5800, sold: 38000, deliveryTime: 'Entrega instantanea', platform: 'Nintendo', region: 'Global', tags: ['oferta'], stock: 999, featured: false },
{ id: 'sub19', name: 'ChatGPT Plus - 1 Mes', description: 'Acceso a GPT-4o, generacion de imagenes, analisis avanzado y uso prioritario.', price: 5.99, originalPrice: 19.99, category: 'subscriptions', subcategory: 'AI', image: '/products/gen/subscriptions-cat.png', rating: 4.8, reviews: 9200, sold: 68000, deliveryTime: 'Entrega instantanea', platform: 'AI', region: 'Global', tags: ['tendencia', 'popular'], stock: 999, featured: true },
{ id: 'sub20', name: 'Midjourney - 1 Mes', description: 'Generacion de imagenes con IA de alta calidad. Acceso a Midjourney V6 y horas ilimitadas.', price: 8.99, originalPrice: 29.99, category: 'subscriptions', subcategory: 'AI', image: '/products/gen/subscriptions-cat.png', rating: 4.7, reviews: 5200, sold: 32000, deliveryTime: 'Entrega instantanea', platform: 'AI', region: 'Global', tags: ['tendencia', 'oferta'], stock: 999, featured: false },
];
export const MARKET_DATA = {
  totalMarketSize: '$522B',
  gamingRevenue: '$225.28B',
  streamingRevenue: '$204.77B',
  digitalProductsGrowth: '12.6%',
  profitMargins: {
    software: { min: 85, max: 95, label: 'Software y Licencias' },
    gaming: { min: 70, max: 90, label: 'Gaming Digital' },
    streaming: { min: 60, max: 85, label: 'Streaming' },
    giftcards: { min: 3, max: 12, label: 'Gift Cards' },
    subscriptions: { min: 50, max: 80, label: 'Suscripciones' },
  },
  topProducts: [
    { name: 'Cuentas de Streaming', revenue: '$47.06B', growth: '+18.2%', margin: '60-85%' },
    { name: 'Skins y V-Bucks', revenue: '$32.5B', growth: '+22.1%', margin: '70-90%' },
    { name: 'Tarjetas de Regalo', revenue: '$28.3B', growth: '+9.8%', margin: '3-12%' },
    { name: 'Licencias Software', revenue: '$45.7B', growth: '+15.3%', margin: '85-95%' },
    { name: 'Suscripciones Gaming', revenue: '$18.9B', growth: '+28.5%', margin: '50-80%' },
    { name: 'Monedas In-Game', revenue: '$15.2B', growth: '+19.7%', margin: '70-90%' },
    { name: 'Cuentas Premium', revenue: '$12.8B', growth: '+14.2%', margin: '65-85%' },
  ],
  regionalDemand: [
    { region: 'Norteamérica', share: 35, trend: 'Estable' },
    { region: 'Asia-Pacífico', share: 38, trend: '+25%' },
    { region: 'Europa', share: 18, trend: '+12%' },
    { region: 'Latinoamérica', share: 6, trend: '+35%' },
    { region: 'África/MEA', share: 3, trend: '+40%' },
  ],
  bestBuys: [
    { product: 'Licencias Windows/Office', cost: '$2-5', sellPrice: '$8-15', margin: '75-90%', reason: 'Demanda masiva global, costo de adquisición extremadamente bajo' },
    { product: 'Suscripciones Netflix/Spotify', cost: '$0.50-1.50', sellPrice: '$3-5', margin: '70-85%', reason: 'Alta rotación, los usuarios renuevan mensualmente' },
    { product: 'V-Bucks / Robux', cost: '$2-3', sellPrice: '$4-6', margin: '50-65%', reason: 'Mercado infantil/juvenil enorme, compra impulsiva frecuente' },
    { product: 'Gift Cards Steam/PlayStation', cost: '$42-46', sellPrice: '$45-50', margin: '5-15%', reason: 'Volumen altísimo, confianza del consumidor, regalo ideal' },
    { product: 'Discord Nitro / YT Premium', cost: '$3-5', sellPrice: '$5-8', margin: '55-65%', reason: 'Crecimiento explosivo en comunidad gamer' },
    { product: 'Cuentas Minecraft Premium', cost: '$2-3', sellPrice: '$4-6', margin: '65-80%', reason: 'Uno de los juegos más vendidos de la historia' },
    { product: 'VPN Suscripciones', cost: '$10-18', sellPrice: '$25-35', margin: '50-65%', reason: 'Demanda creciente por privacidad y acceso geo-restringido' },
  ],
};

