#!/bin/bash
# Generate ALL product images using z-ai image CLI
# Each image is a professional digital product card design

cd /home/z/my-project
DIR="./public/products/gen"
mkdir -p "$DIR"

PROMPTS=(
  "eafc25|Professional EA FC 25 FC Points card, orange and teal gradient with soccer ball, FIFA ultimate team premium design"
  "apex|Professional Apex Legends coins card, red and dark gradient with legend character silhouette, winged jump jet effect"
  "pubgm|Professional PUBG Mobile UC card, yellow and military olive gradient with airdrop crate, battle royale gaming aesthetic"
  "cod|Professional Call of Duty COD Points card, dark green and black tactical design with military elements, FPS game premium"
  "freefire|Professional Free Fire diamonds card, orange and flame gradient with fire effect, battle royale mobile game aesthetic"
  "amongus|Professional Among Us stars card, red space station background with crewmate character silhouette, fun colorful game design"
  "clashroyale|Professional Clash Royale gems card, blue and gold with tower and chest elements, mobile strategy game premium design"
  "mobilelegends|Professional Mobile Legends Bang Bang diamonds card, blue and purple with hero character silhouette, MOBA mobile aesthetic"
  "brawlstars|Professional Brawl Stars gems card, yellow and purple starburst with brawler character, fun colorful game design"
  "cs2|Professional Counter-Strike 2 skin card, orange and dark with weapon silhouette, tactical FPS gaming premium aesthetic"
  "gtav|Professional GTA V Shark Card, teal and gold with sports car silhouette, palm trees, open world game premium design"
  "honkai|Professional Honkai Star Rail card, purple and gold cosmic space design with train silhouette, anime gacha premium aesthetic"
  "wuthering|Professional Wuthering Waves card, cyan and white with ethereal spirit elements, anime action game premium design"
  "coc|Professional Clash of Clans gems card, gold and dark with barbarian king and wizard tower, mobile strategy game premium"
  "fifamobile|Professional FIFA Mobile coins card, green and gold with soccer stadium silhouette, mobile sports game premium"
  "wildrift|Professional League of Legends Wild Rift card, blue and purple with champion silhouette, mobile MOBA game premium"
  "diablo4|Professional Diablo IV card, dark red and black with demon silhouette, hellfire effect, dark fantasy game premium"
  "overwatch2|Professional Overwatch 2 coins card, orange and blue with hero silhouette, team shooter game premium design"
  "rocketleague|Professional Rocket League credits card, blue and orange with rocket car, boost effect, vehicular soccer game premium"
  "destiny2|Professional Destiny 2 silver card, white and gold with guardian silhouette, space sci-fi game premium aesthetic"
  "warzone|Professional Call of Duty Warzone card, dark military green with soldier silhouette, tactical FPS battle royale premium"
  "pokemon|Professional Pokemon Unite card, yellow and blue with Pikachu silhouette, Pokemon battle arena game premium"
  "arenaofvalor|Professional Arena of Valor card, blue and gold with hero silhouette, mobile MOBA game premium design"
  "standoff2|Professional Standoff 2 card, gray and red with weapon and skin elements, mobile FPS game premium design"
  "brawlhalla|Professional Brawlhalla card, purple and blue with warrior silhouette, platform fighter game premium design"
  "deadbydaylight|Professional Dead by Daylight card, dark red and black with killer and survivor silhouettes, horror game premium aesthetic"
  "fallguys|Professional Fall Guys card, pink and blue with bean character silhouette, fun party game premium colorful design"
  "rainbowsix|Professional Rainbow Six Siege card, blue and orange with operator silhouette, tactical FPS game premium design"
  "hearthstone|Professional Hearthstone card, golden brown with card and fire elements, digital card game premium fantasy design"
  "pubgpc|Professional PUBG PC card, dark yellow and black with crate and weapons, battle royale PC game premium aesthetic"
  "warframe|Professional Warframe Platinum card, white and teal with Warframe silhouette, space ninja game premium sci-fi design"
  "netflix|Professional Netflix subscription gift card, classic red and black design with N logo, premium streaming service aesthetic"
  "spotify|Professional Spotify Premium gift card, vibrant green and black design with music notes, audio streaming service premium aesthetic"
  "disney|Professional Disney Plus subscription card, blue and purple magical design with castle silhouette, premium streaming service aesthetic"
  "hbomax|Professional HBO Max subscription card, deep purple and gold premium design, premium streaming service luxurious aesthetic"
  "crunchyroll|Professional Crunchyroll Premium card, orange and black with anime character silhouette, anime streaming service premium design"
  "amazonprime|Professional Amazon Prime Video card, blue and black with play button, premium streaming service modern design"
  "paramount|Professional Paramount Plus card, blue and white mountain design with star logo, premium streaming service premium aesthetic"
  "appletv|Professional Apple TV Plus card, dark gray and white minimalist Apple design, premium streaming service elegant aesthetic"
  "twitch|Professional Twitch subscription card, purple and white with streaming camera and chat icons, live streaming premium design"
  "hulu|Professional Hulu subscription card, green and white with TV screen elements, premium streaming service colorful design"
  "maxstream|Professional Max streaming card, dark blue and indigo with premium cinematic design, HBO streaming premium aesthetic"
  "peacock|Professional Peacock Premium card, yellow and purple gradient with peacock feather elements, streaming service colorful design"
  "dazn|Professional DAZN subscription card, red and black with sports elements, live sports streaming premium design"
  "starplus|Professional Star Plus card, blue and teal with star and entertainment elements, Disney streaming premium design"
  "steam|Professional Steam wallet gift card, dark blue and gray with Steam logo style, gaming platform premium digital design"
  "playstation|Professional PlayStation Store gift card, blue and black with PS controller silhouette, Sony gaming premium design"
  "xbox|Professional Xbox gift card, green and black with Xbox controller silhouette, Microsoft gaming premium design"
  "nintendo|Professional Nintendo eShop gift card, red and white with Switch console silhouette, Nintendo gaming premium colorful design"
  "googleplay|Professional Google Play gift card, multicolor gradient with Play Store triangle, Android app store premium design"
  "apple|Professional Apple App Store iTunes gift card, minimalist white and gray with Apple logo style, Apple premium elegant design"
  "amazon|Professional Amazon gift card, orange and teal with shopping cart and box, e-commerce premium modern design"
  "epicgames|Professional Epic Games gift card, dark with Unreal Engine logo style, gaming store premium digital design"
  "riotgames|Professional Riot Games gift card, red and white with multiple game icons, gaming publisher premium design"
  "discord|Professional Discord Nitro card, blurple purple and white with Discord logo style, chat app premium modern design"
  "visa|Professional Visa prepaid gift card, blue and gold with Visa logo, financial payment card premium elegant design"
  "paypal|Professional PayPal gift card, blue and gold with PayPal logo, digital payment premium modern design"
  "xboxgp|Professional Xbox Game Pass card, green and black with game controller and cloud gaming elements, subscription gaming premium design"
  "blizzard|Professional Blizzard Battle.net gift card, dark blue with game icons, gaming publisher premium digital design"
  "windows|Professional Windows 11 Pro license card, blue gradient with Windows logo, Microsoft OS premium professional design"
  "microsoft365|Professional Microsoft 365 subscription card, red and blue with Office app icons, productivity suite premium design"
  "adobecc|Professional Adobe Creative Cloud card, dark red and purple with Adobe icons, creative software premium design"
  "nordvpn|Professional NordVPN subscription card, dark blue with world map and shield, VPN security premium digital design"
  "kaspersky|Professional Kaspersky security card, green and white with shield icon, antivirus security premium design"
  "malwarebytes|Professional Malwarebytes card, blue and white with bug icon, cybersecurity premium clean design"
  "office2024|Professional Microsoft Office 2024 card, orange and white with Word Excel PowerPoint icons, productivity premium design"
  "avast|Professional Avast security card, orange and dark with shield icon, antivirus security premium protective design"
  "bitdefender|Professional Bitdefender card, red and black with dragon shield, cybersecurity premium powerful design"
  "norton|Professional Norton 360 card, yellow and black with circular shield, antivirus security premium trusted design"
  "expressvpn|Professional ExpressVPN card, green and dark with network globe, VPN privacy premium secure design"
  "surfshark|Professional Surfshark VPN card, teal and dark with wave and shark elements, VPN privacy premium design"
  "mcafee|Professional McAfee security card, red and white with shield, antivirus security premium enterprise design"
  "eset|Professional ESET security card, blue and white with shield logo, antivirus security premium clean design"
  "youtube|Professional YouTube Premium card, red and white with play button, video streaming premium modern design"
  "canva|Professional Canva Pro card, purple and white with design tools, creative design platform premium aesthetic"
  "eaplay|Professional EA Play Pro card, dark with EA game controller, gaming subscription premium design"
  "chatgpt|Professional ChatGPT Plus card, dark teal with AI brain and chat elements, artificial intelligence premium modern design"
  "cloudgaming|Professional GeForce NOW cloud gaming card, green with cloud and game controller, cloud gaming premium futuristic design"
  "icloud|Professional iCloud Plus card, white and blue with cloud storage icon, Apple cloud premium clean design"
  "medium|Professional Medium membership card, black and white minimalist with writing elements, publishing platform premium elegant design"
  "duolingo|Professional Duolingo Plus card, green and white with owl mascot, language learning app premium fun design"
  "notion|Professional Notion Pro card, black and white with workspace elements, productivity tool premium modern design"
  "midjourney|Professional Midjourney AI art card, blue and purple with AI generated artwork, AI art tool premium creative design"
  "github|Professional GitHub Copilot card, dark gray with code and GitHub octocat, developer tools premium modern design"
  "dropbox|Professional Dropbox Plus card, blue and white with cloud and folder, cloud storage premium clean design"
  "figma|Professional Figma Pro card, purple and white with design tool elements, UI design platform premium modern design"
  "slack|Professional Slack Business card, purple and green with chat and channel icons, team communication premium design"
  "zoom|Professional Zoom Pro card, blue and white with video camera, video conferencing premium clean design"
  "instagram|Professional Instagram growth card, pink purple and orange gradient with camera and heart, social media premium vibrant design"
  "tiktok|Professional TikTok growth card, black and cyan with music note, social media premium modern design"
  "twitter|Professional Twitter X growth card, black and white with X logo, social media premium modern design"
  "youtubeacc|Professional YouTube channel growth card, red and white with play button and subscribers, social media premium design"
  "facebook|Professional Facebook growth card, blue and white with like and share icons, social media premium design"
  "twitchacc|Professional Twitch growth card, purple and white with streaming and chat, live streaming premium design"
  "discordacc|Professional Discord server card, blurple purple with server boost and members, community premium design"
  "spotifyacc|Professional Spotify growth card, green and black with music and followers, music platform premium design"
  "snapchat|Professional Snapchat growth card, yellow and white with ghost icon, social media premium fun design"
  "telegram|Professional Telegram growth card, blue and white with paper plane and chat, messaging app premium design"
  "linkedin|Professional LinkedIn growth card, blue and white with professional network icons, business social premium design"
  "pinterest|Professional Pinterest growth card, red and white with pin and board icons, social media premium design"
  "reddit|Professional Reddit growth card, orange and white with upvote arrow, community forum premium design"
  "threads|Professional Threads Meta card, black and white with @ symbol, social media premium modern design"
  "whatsapp|Professional WhatsApp growth card, green and white with phone and chat, messaging app premium design"
)

for item in "${PROMPTS[@]}"; do
  IFS='|' read -r key prompt <<< "$item"
  outfile="$DIR/${key}.png"
  [ -f "$outfile" ] && echo "[SKIP] $key" && continue
  z-ai image -p "$prompt" -o "$outfile" -s 1024x1024 2>/dev/null
  if [ $? -eq 0 ]; then
    echo "[OK] $key"
  else
    echo "[FAIL] $key - waiting..."
    sleep 15
    z-ai image -p "$prompt" -o "$outfile" -s 1024x1024 2>/dev/null
    [ $? -eq 0 ] && echo "[RETRY OK] $key" || echo "[RETRY FAIL] $key"
  fi
  sleep 5
done
echo "=== GENERATION COMPLETE ==="
ls -la "$DIR" | wc -l
